# For which inventories should the restrictions here apply?
# Allowed values: FURNACE, HOPPER, DROPPER, BREWING, DISPENSER, CHEST, ENDER_CHEST, ANVIL, WORKBENCH, BEACON, ENCHANTING, CRAFTING, MERCHANT
# WORKBENCH is a crafting table; CRAFTING is the survival crafting inventory; MERCHANT is villager trading.
# Note: the plugin doesn't care about lower or UPPER case.
inventories:
- furnace
- hopper
- dropper
- brewing
- dispenser
- chest
- ender_chest

# Should all items be blocked from the containers except those on this list?
# If this is true, all items will be blocked from containers except those listed below.
# If this is false, only the items on the list below will be blocked from containers.
blockallitems: false

# Which items should be in the list of items?
items:
- ==: org.bukkit.inventory.ItemStack
  type: LAPIS_BLOCK
