name: ContainerBlocker
main: net.omniscimus.containerblocker.ContainerBlocker
version: 1.0.0
description: This plugin prevents players from placing certain items in containers.
author: Omniscimus
commands:
   containerblocker:
      description: The main command for ContainerBlocker.
      usage: /containerblocker help